name: "IaC Security - Checkov"

on:
  workflow_call

permissions:
  issues: write
  contents: read
  security-events: write

jobs:
  checkov:
    name: Checkov Scan
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read
      security-events: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@3203f966a7ccd680cd8f6aaa3c3c5b0b3e9afa32 # master
        with:
          directory: .
          download_external_modules: true
          framework: terraform,kubernetes,github_actions
          output_format: cli,sarif
          output_file_path: console,results.sarif
          soft_fail: true 

      - name: Carica i risultati su GitHub Security
        uses: github/codeql-action/upload-sarif@v4 
        if: always() # Esegue l'upload anche se Checkov trova degli errori
        with:
          sarif_file: results.sarif
          category: checkov-iac 
          wait-for-processing: true