name: Master Security Pipeline

on:
    push:
        branches: [ "main", "master" ]
    pull_request:
        branches: [ "main", "master" ]

permissions:
    contents: read
    security-events: write
    actions: read
concurrency:
    group: ${{ github.workflow }}-${{github.ref}}
    cancel-in-progress: true

jobs:
    gitleaks:
        name: run gitLeaks
        uses: ./.github/workflows/gitLeaks.yml
        secrets: inherit

    spectral: 
        name: run Spectral
        uses: ./.github/workflows/spectral.yml 

    codeql:
        name: run CodeQL
        needs: [gitleaks , spectral]
        uses: ./.github/workflows/codeql.yml 

    sonarqube:
        name: run sonarqube
        needs: [gitleaks , spectral]
        uses: ./.github/workflows/sonarqube.yml 
        secrets: inherit
        
    checkov:
        name: run chechov
        needs: [gitleaks , spectral]
        uses: ./.github/workflows/checkov.yml 

    Trivy:
        name: run trivy
        needs: [gitleaks , spectral]
        uses: ./.github/workflows/trivy.yml 