name: SonarQube Quality Scan

on:
  workflow_call

jobs:
  sonar-scan:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write 
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Esegui scansione SonarQube
        uses: sonarsource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        with:
          args: >
            -Dsonar.organization=lucazana14
            -Dsonar.projectKey=lucazana14_VAmPI
            -Dsonar.sources=.
            -Dsonar.python.version=3
            -Dsonar.branch.name=${{github.ref_name}}

      - name: Convert SonarCloud issues to SARIF
        if: always()
        env:
            # Sincronizziamo al millimetro i nomi con lo script Python
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_ORG: "lucazana14"
            SONAR_PROJECT_KEY: "lucazana14_VAmPI"
            SONAR_HOST_URL: "https://sonarcloud.io"
        run: |
            python3 .github/scripts/sonar_to_sarif.py

      - name: Carica i risultati su GitHub Security
        uses: github/codeql-action/upload-sarif@v4 
        if: always()
        with:
          sarif_file: sonarcloud.sarif